server:
  port: 8080

spring:
  main:
    banner-mode: OFF
    web-application-type: REACTIVE
  application:
    name: app-spring-gateway

gateway:
  routes:
    - name: users
      protocol: http
      host: localhost
      port: 3001
      publicPath: /api/users
      realPath: /moock/users
      stripPrefix: 2

    - name: products
      protocol: http
      host: localhost
      port: 3001
      publicPath: /api/books
      realPath: /moock/books
      stripPrefix: 2

---

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: users_route
              uri: ${gateway.routes[0].protocol}://${gateway.routes[0].host}:${gateway.routes[0].port}
              predicates:
                - Path=${gateway.routes[0].publicPath}
              methods:
                - GET
              filters:
                - StripPrefix=${gateway.routes[0].stripPrefix}
                - SetPath=${gateway.routes[0].realPath}

            - id: books_route
              uri: ${gateway.routes[1].protocol}://${gateway.routes[1].host}:${gateway.routes[1].port}
              predicates:
                - Path=${gateway.routes[1].publicPath}
              methods:
                - GET
              filters:
                - StripPrefix=${gateway.routes[1].stripPrefix}
                - SetPath=${gateway.routes[1].realPath}

---

management:
  endpoints:
    web:
      exposure:
        include: "*" # Expõe todos os endpoints do Actuator (incluindo /actuator/prometheus para métricas)
  logging:
    export:
      enabled: false
  tracing:
    enabled: false
    sampling:
      probability: 1.0 # 100% de amostragem para traces (para lab, pode ser menor em produção)
  datadog:
    metrics:
      export:
        enabled: false
        step: 30s # Intervalo de envio de métricas para o Datadog
        api-key: ${DD_API_KEY}
        application-key: ${DD_APPS_KEY}
        uri: https://${DD_URI_SITE}

logging:
  level:
    root: INFO
    # br.com.jhegner.k8slabs: INFO
