server:
  port: 8080

spring:
  main:
    banner-mode: OFF
    web-application-type: REACTIVE
  application:
    name: app-spring-gateway

---

mockapi:
  protocol: "https"
  host: ${MOCKAPI_PROJECT_SECRET}
  prefix: ${MOCKAPI_PATH_PREFIX}
  port: 443
  version: ${MOCKAPI_VERSION}
  base-url: "${mockapi.protocol}://${mockapi.host}.${mockapi.prefix}:${mockapi.port}/${mockapi.version}"

---

spring:
  cloud:
    gateway:
      server:
        webflux:          
          routes:
            - id: users_route # rest
              uri: ${mockapi.base-url}
              predicates:
                - Path=/api/users # path public que será exposto pelo gateway
              methods:
                - GET
              filters:
                - StripPrefix=2 # Remove /api/users do path antes de encaminhar
                - SetPath=/users

            - id: products_route
              uri: ${mockapi.base-url}
              predicates:
                - Path=/api/products # path public que será exposto pelo gateway
              filters:
                - StripPrefix=2
                - SetPath=/users

management:
  endpoints:
    web:
      exposure:
        include: "actuator,health,prometheus"

logging:
  structured:
    format:
      console: ecs # Formato de log estruturado para console - format Elastic Common Schema (ECS)        
  level:
   br.com.jhegner.k8slabs: INFO